Shader "Custom/Blur" {
	Properties {
		_Factor ("Factor", Range(0, 50)) = 1
	}
	SubShader {
		Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
		GrabPass {
		}
		Pass {
			Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
			ColorMask 0 -1
			ZTest Always
			Cull Front
			GpuProgramID 4137
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_input v0.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o1.zw, r0.zzzw
					add o1.xy, r1.yyyy, r1.xzxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[68], dynamicIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_input v0.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					ishl r1.x, cb2[0].x, l(2)
					mul r2.xyzw, r0.yyyy, cb1[r1.x + 25].xyzw
					mad r2.xyzw, cb1[r1.x + 24].xyzw, r0.xxxx, r2.xyzw
					mad r2.xyzw, cb1[r1.x + 26].xyzw, r0.zzzz, r2.xyzw
					mad r0.xyzw, cb1[r1.x + 27].xyzw, r0.wwww, r2.xyzw
					mov o0.xyzw, r0.xyzw
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					add r0.xy, r1.yyyy, r1.xzxx
					mov r1.x, cb2[0].x
					mul r1.yz, r0.wwww, cb1[r1.x + 66].zzwz
					mad o1.xy, r0.xyxx, cb1[r1.x + 66].xyxx, r1.yzyy
					mov o1.zw, r0.zzzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyw
					dcl_output o0.xyzw
					dcl_temps 4
					mov r0.yw, v1.yyyy
					mul r1.x, cb0[2].x, cb0[3].x
					mad r2.xyzw, r1.xxxx, l(-3.000000, 4.000000, 3.000000, -2.000000), v1.xxxx
					mov r0.xz, r2.yyzy
					div r0.xyzw, r0.xyzw, v1.wwww
					sample r3.xyzw, r0.zwzz, t0.xyzw, s0
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mul r3.xyzw, r3.xyzw, l(0.090000, 0.090000, 0.090000, 0.090000)
					mad r0.xyzw, r0.xyzw, l(0.050000, 0.050000, 0.050000, 0.050000), r3.xyzw
					mad r3.x, r1.x, l(2.000000), v1.x
					mad r2.z, r1.x, l(-4.000000), v1.x
					mov r3.yw, v1.yyyy
					div r1.xy, r3.xyxx, v1.wwww
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					mad r0.xyzw, r1.xyzw, l(0.120000, 0.120000, 0.120000, 0.120000), r0.xyzw
					mad r3.z, cb0[2].x, cb0[3].x, v1.x
					div r1.xy, r3.zwzz, v1.wwww
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					mad r0.xyzw, r1.xyzw, l(0.150000, 0.150000, 0.150000, 0.150000), r0.xyzw
					div r1.xy, v1.xyxx, v1.wwww
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					mad r0.xyzw, r1.xyzw, l(0.180000, 0.180000, 0.180000, 0.180000), r0.xyzw
					mad r1.x, -cb0[2].x, cb0[3].x, v1.x
					mov r1.yw, v1.yyyy
					div r1.xy, r1.xyxx, v1.wwww
					sample r3.xyzw, r1.xyxx, t0.xyzw, s0
					mad r0.xyzw, r3.xyzw, l(0.150000, 0.150000, 0.150000, 0.150000), r0.xyzw
					mov r1.z, r2.w
					div r1.xy, r1.zwzz, v1.wwww
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					mad r0.xyzw, r1.xyzw, l(0.120000, 0.120000, 0.120000, 0.120000), r0.xyzw
					mov r2.yw, v1.yyyy
					div r1.xyzw, r2.xyzw, v1.wwww
					sample r2.xyzw, r1.zwzz, t0.xyzw, s0
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					mad r0.xyzw, r1.xyzw, l(0.090000, 0.090000, 0.090000, 0.090000), r0.xyzw
					mad o0.xyzw, r2.xyzw, l(0.050000, 0.050000, 0.050000, 0.050000), r0.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyw
					dcl_output o0.xyzw
					dcl_temps 4
					mov r0.yw, v1.yyyy
					mul r1.x, cb0[2].x, cb0[3].x
					mad r2.xyzw, r1.xxxx, l(-3.000000, 4.000000, 3.000000, -2.000000), v1.xxxx
					mov r0.xz, r2.yyzy
					div r0.xyzw, r0.xyzw, v1.wwww
					sample r3.xyzw, r0.zwzz, t0.xyzw, s0
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mul r3.xyzw, r3.xyzw, l(0.090000, 0.090000, 0.090000, 0.090000)
					mad r0.xyzw, r0.xyzw, l(0.050000, 0.050000, 0.050000, 0.050000), r3.xyzw
					mad r3.x, r1.x, l(2.000000), v1.x
					mad r2.z, r1.x, l(-4.000000), v1.x
					mov r3.yw, v1.yyyy
					div r1.xy, r3.xyxx, v1.wwww
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					mad r0.xyzw, r1.xyzw, l(0.120000, 0.120000, 0.120000, 0.120000), r0.xyzw
					mad r3.z, cb0[2].x, cb0[3].x, v1.x
					div r1.xy, r3.zwzz, v1.wwww
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					mad r0.xyzw, r1.xyzw, l(0.150000, 0.150000, 0.150000, 0.150000), r0.xyzw
					div r1.xy, v1.xyxx, v1.wwww
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					mad r0.xyzw, r1.xyzw, l(0.180000, 0.180000, 0.180000, 0.180000), r0.xyzw
					mad r1.x, -cb0[2].x, cb0[3].x, v1.x
					mov r1.yw, v1.yyyy
					div r1.xy, r1.xyxx, v1.wwww
					sample r3.xyzw, r1.xyxx, t0.xyzw, s0
					mad r0.xyzw, r3.xyzw, l(0.150000, 0.150000, 0.150000, 0.150000), r0.xyzw
					mov r1.z, r2.w
					div r1.xy, r1.zwzz, v1.wwww
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					mad r0.xyzw, r1.xyzw, l(0.120000, 0.120000, 0.120000, 0.120000), r0.xyzw
					mov r2.yw, v1.yyyy
					div r1.xyzw, r2.xyzw, v1.wwww
					sample r2.xyzw, r1.zwzz, t0.xyzw, s0
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					mad r0.xyzw, r1.xyzw, l(0.090000, 0.090000, 0.090000, 0.090000), r0.xyzw
					mad o0.xyzw, r2.xyzw, l(0.050000, 0.050000, 0.050000, 0.050000), r0.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		GrabPass {
		}
		Pass {
			Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
			Cull Front
			GpuProgramID 99583
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_input v0.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o1.zw, r0.zzzw
					add o1.xy, r1.yyyy, r1.xzxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[68], dynamicIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_input v0.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					ishl r1.x, cb2[0].x, l(2)
					mul r2.xyzw, r0.yyyy, cb1[r1.x + 25].xyzw
					mad r2.xyzw, cb1[r1.x + 24].xyzw, r0.xxxx, r2.xyzw
					mad r2.xyzw, cb1[r1.x + 26].xyzw, r0.zzzz, r2.xyzw
					mad r0.xyzw, cb1[r1.x + 27].xyzw, r0.wwww, r2.xyzw
					mov o0.xyzw, r0.xyzw
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					add r0.xy, r1.yyyy, r1.xzxx
					mov r1.x, cb2[0].x
					mul r1.yz, r0.wwww, cb1[r1.x + 66].zzwz
					mad o1.xy, r0.xyxx, cb1[r1.x + 66].xyxx, r1.yzyy
					mov o1.zw, r0.zzzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyw
					dcl_output o0.xyzw
					dcl_temps 5
					mov r0.xz, v1.xxxx
					mul r1.x, cb0[2].y, cb0[3].x
					mad r2.xyzw, r1.xxxx, l(4.000000, 3.000000, -2.000000, -3.000000), v1.yyyy
					mov r0.yw, r2.xxxy
					div r0.xyzw, r0.xyzw, v1.wwww
					sample r3.xyzw, r0.zwzz, t0.xyzw, s0
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mul r3.xyzw, r3.xyzw, l(0.090000, 0.090000, 0.090000, 0.090000)
					mad r0.xyzw, r0.xyzw, l(0.050000, 0.050000, 0.050000, 0.050000), r3.xyzw
					mad r3.y, r1.x, l(2.000000), v1.y
					mad r1.w, r1.x, l(-4.000000), v1.y
					mov r3.xz, v1.xxxx
					div r2.xy, r3.xyxx, v1.wwww
					sample r4.xyzw, r2.xyxx, t0.xyzw, s0
					mad r0.xyzw, r4.xyzw, l(0.120000, 0.120000, 0.120000, 0.120000), r0.xyzw
					mad r3.w, cb0[2].y, cb0[3].x, v1.y
					div r2.xy, r3.zwzz, v1.wwww
					sample r3.xyzw, r2.xyxx, t0.xyzw, s0
					mad r0.xyzw, r3.xyzw, l(0.150000, 0.150000, 0.150000, 0.150000), r0.xyzw
					div r2.xy, v1.xyxx, v1.wwww
					sample r3.xyzw, r2.xyxx, t0.xyzw, s0
					mad r0.xyzw, r3.xyzw, l(0.180000, 0.180000, 0.180000, 0.180000), r0.xyzw
					mad r3.y, -cb0[2].y, cb0[3].x, v1.y
					mov r3.xz, v1.xxxx
					div r2.xy, r3.xyxx, v1.wwww
					sample r4.xyzw, r2.xyxx, t0.xyzw, s0
					mad r0.xyzw, r4.xyzw, l(0.150000, 0.150000, 0.150000, 0.150000), r0.xyzw
					mov r3.w, r2.z
					mov r1.y, r2.w
					div r2.xy, r3.zwzz, v1.wwww
					sample r2.xyzw, r2.xyxx, t0.xyzw, s0
					mad r0.xyzw, r2.xyzw, l(0.120000, 0.120000, 0.120000, 0.120000), r0.xyzw
					mov r1.xz, v1.xxxx
					div r1.xyzw, r1.xyzw, v1.wwww
					sample r2.xyzw, r1.zwzz, t0.xyzw, s0
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					mad r0.xyzw, r1.xyzw, l(0.090000, 0.090000, 0.090000, 0.090000), r0.xyzw
					mad o0.xyzw, r2.xyzw, l(0.050000, 0.050000, 0.050000, 0.050000), r0.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyw
					dcl_output o0.xyzw
					dcl_temps 5
					mov r0.xz, v1.xxxx
					mul r1.x, cb0[2].y, cb0[3].x
					mad r2.xyzw, r1.xxxx, l(4.000000, 3.000000, -2.000000, -3.000000), v1.yyyy
					mov r0.yw, r2.xxxy
					div r0.xyzw, r0.xyzw, v1.wwww
					sample r3.xyzw, r0.zwzz, t0.xyzw, s0
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mul r3.xyzw, r3.xyzw, l(0.090000, 0.090000, 0.090000, 0.090000)
					mad r0.xyzw, r0.xyzw, l(0.050000, 0.050000, 0.050000, 0.050000), r3.xyzw
					mad r3.y, r1.x, l(2.000000), v1.y
					mad r1.w, r1.x, l(-4.000000), v1.y
					mov r3.xz, v1.xxxx
					div r2.xy, r3.xyxx, v1.wwww
					sample r4.xyzw, r2.xyxx, t0.xyzw, s0
					mad r0.xyzw, r4.xyzw, l(0.120000, 0.120000, 0.120000, 0.120000), r0.xyzw
					mad r3.w, cb0[2].y, cb0[3].x, v1.y
					div r2.xy, r3.zwzz, v1.wwww
					sample r3.xyzw, r2.xyxx, t0.xyzw, s0
					mad r0.xyzw, r3.xyzw, l(0.150000, 0.150000, 0.150000, 0.150000), r0.xyzw
					div r2.xy, v1.xyxx, v1.wwww
					sample r3.xyzw, r2.xyxx, t0.xyzw, s0
					mad r0.xyzw, r3.xyzw, l(0.180000, 0.180000, 0.180000, 0.180000), r0.xyzw
					mad r3.y, -cb0[2].y, cb0[3].x, v1.y
					mov r3.xz, v1.xxxx
					div r2.xy, r3.xyxx, v1.wwww
					sample r4.xyzw, r2.xyxx, t0.xyzw, s0
					mad r0.xyzw, r4.xyzw, l(0.150000, 0.150000, 0.150000, 0.150000), r0.xyzw
					mov r3.w, r2.z
					mov r1.y, r2.w
					div r2.xy, r3.zwzz, v1.wwww
					sample r2.xyzw, r2.xyxx, t0.xyzw, s0
					mad r0.xyzw, r2.xyzw, l(0.120000, 0.120000, 0.120000, 0.120000), r0.xyzw
					mov r1.xz, v1.xxxx
					div r1.xyzw, r1.xyzw, v1.wwww
					sample r2.xyzw, r1.zwzz, t0.xyzw, s0
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					mad r0.xyzw, r1.xyzw, l(0.090000, 0.090000, 0.090000, 0.090000), r0.xyzw
					mad o0.xyzw, r2.xyzw, l(0.050000, 0.050000, 0.050000, 0.050000), r0.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}