Shader "FX/Gem" {
	Properties {
		_Color ("Color", Vector) = (1,1,1,1)
		_ReflectionStrength ("Reflection Strength", Range(0, 2)) = 1
		_EnvironmentLight ("Environment Light", Range(0, 2)) = 1
		_Emission ("Emission", Range(0, 2)) = 0
		[NoScaleOffset] _RefractTex ("Refraction Texture", Cube) = "" {}
	}
	SubShader {
		Tags { "QUEUE" = "Transparent" }
		Pass {
			Tags { "QUEUE" = "Transparent" }
			ZWrite Off
			Cull Front
			GpuProgramID 49105
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[8], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyz
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mul r0.xyz, cb0[4].yyyy, cb1[5].xyzx
					mad r0.xyz, cb1[4].xyzx, cb0[4].xxxx, r0.xyzx
					mad r0.xyz, cb1[6].xyzx, cb0[4].zzzz, r0.xyzx
					add r0.xyz, r0.xyzx, cb1[7].xyzx
					add r0.xyz, r0.xyzx, -v0.xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.w, r0.xyzx, v1.xyzx
					add r0.w, r0.w, r0.w
					mad r0.xyz, v1.xyzx, -r0.wwww, r0.xyzx
					mul r1.xyz, -r0.yyyy, cb1[1].xyzx
					mad r0.xyw, cb1[0].xyxz, -r0.xxxx, r1.xyxz
					mad o1.xyz, cb1[2].xyzx, -r0.zzzz, r0.xywx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[8], immediateIndexed
					dcl_constantbuffer CB1[66], dynamicIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyz
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					ishl r1.x, cb2[0].x, l(2)
					mul r2.xyzw, r0.yyyy, cb1[r1.x + 25].xyzw
					mad r2.xyzw, cb1[r1.x + 24].xyzw, r0.xxxx, r2.xyzw
					mad r2.xyzw, cb1[r1.x + 26].xyzw, r0.zzzz, r2.xyzw
					mad o0.xyzw, cb1[r1.x + 27].xyzw, r0.wwww, r2.xyzw
					mov r0.x, cb2[0].x
					mul r0.yzw, cb0[5].xxyz, cb1[r0.x + 64].yyyy
					mad r0.yzw, cb0[4].xxyz, cb1[r0.x + 64].xxxx, r0.yyzw
					mad r0.xyz, cb0[6].xyzx, cb1[r0.x + 64].zzzz, r0.yzwy
					add r0.xyz, r0.xyzx, cb0[7].xyzx
					add r0.xyz, r0.xyzx, -v0.xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.w, r0.xyzx, v1.xyzx
					add r0.w, r0.w, r0.w
					mad r0.xyz, v1.xyzx, -r0.wwww, r0.xyzx
					mul r1.xyz, -r0.yyyy, cb0[1].xyzx
					mad r0.xyw, cb0[0].xyxz, -r0.xxxx, r1.xyxz
					mad o1.xyz, cb0[2].xyzx, -r0.zzzz, r0.xywx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texturecube (float,float,float,float) t0
					dcl_resource_texturecube (float,float,float,float) t1
					dcl_input_ps linear v1.xyz
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v1.xyzx, t1.xyzw, s0
					add r0.w, r0.w, l(-1.000000)
					mad r0.w, cb1[3].w, r0.w, l(1.000000)
					log r0.w, r0.w
					mul r0.w, r0.w, cb1[3].y
					exp r0.w, r0.w
					mul r0.w, r0.w, cb1[3].x
					mul r0.xyz, r0.xyzx, r0.wwww
					mad r0.xyz, r0.xyzx, cb0[3].xxxx, cb0[3].yyyy
					sample r1.xyzw, v1.xyzx, t0.xyzw, s1
					mul r1.xyz, r1.xyzx, cb0[2].xyzx
					mul o0.xyz, r0.xyzx, r1.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texturecube (float,float,float,float) t0
					dcl_resource_texturecube (float,float,float,float) t1
					dcl_input_ps linear v1.xyz
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v1.xyzx, t1.xyzw, s0
					add r0.w, r0.w, l(-1.000000)
					mad r0.w, cb1[3].w, r0.w, l(1.000000)
					log r0.w, r0.w
					mul r0.w, r0.w, cb1[3].y
					exp r0.w, r0.w
					mul r0.w, r0.w, cb1[3].x
					mul r0.xyz, r0.xyzx, r0.wwww
					mad r0.xyz, r0.xyzx, cb0[3].xxxx, cb0[3].yyyy
					sample r1.xyzw, v1.xyzx, t0.xyzw, s1
					mul r1.xyz, r1.xyzx, cb0[2].xyzx
					mul o0.xyz, r0.xyzx, r1.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			Tags { "QUEUE" = "Transparent" }
			Blend One One, One One
			GpuProgramID 94879
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					// TEXCOORD                 1      w        1     NONE   float      w
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[8], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyz
					dcl_output o1.w
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mul r0.xyz, cb0[4].yyyy, cb1[5].xyzx
					mad r0.xyz, cb1[4].xyzx, cb0[4].xxxx, r0.xyzx
					mad r0.xyz, cb1[6].xyzx, cb0[4].zzzz, r0.xyzx
					add r0.xyz, r0.xyzx, cb1[7].xyzx
					add r0.xyz, r0.xyzx, -v0.xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.w, r0.xyzx, v1.xyzx
					add r1.x, r0.w, r0.w
					mov_sat r0.w, r0.w
					add o1.w, -r0.w, l(1.000000)
					mad r0.xyz, v1.xyzx, -r1.xxxx, r0.xyzx
					mul r1.xyz, -r0.yyyy, cb1[1].xyzx
					mad r0.xyw, cb1[0].xyxz, -r0.xxxx, r1.xyxz
					mad o1.xyz, cb1[2].xyzx, -r0.zzzz, r0.xywx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					// TEXCOORD                 1      w        1     NONE   float      w
					//
					vs_4_0
					dcl_constantbuffer CB0[8], immediateIndexed
					dcl_constantbuffer CB1[66], dynamicIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyz
					dcl_output o1.w
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					ishl r1.x, cb2[0].x, l(2)
					mul r2.xyzw, r0.yyyy, cb1[r1.x + 25].xyzw
					mad r2.xyzw, cb1[r1.x + 24].xyzw, r0.xxxx, r2.xyzw
					mad r2.xyzw, cb1[r1.x + 26].xyzw, r0.zzzz, r2.xyzw
					mad o0.xyzw, cb1[r1.x + 27].xyzw, r0.wwww, r2.xyzw
					mov r0.x, cb2[0].x
					mul r0.yzw, cb0[5].xxyz, cb1[r0.x + 64].yyyy
					mad r0.yzw, cb0[4].xxyz, cb1[r0.x + 64].xxxx, r0.yyzw
					mad r0.xyz, cb0[6].xyzx, cb1[r0.x + 64].zzzz, r0.yzwy
					add r0.xyz, r0.xyzx, cb0[7].xyzx
					add r0.xyz, r0.xyzx, -v0.xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.w, r0.xyzx, v1.xyzx
					add r1.x, r0.w, r0.w
					mov_sat r0.w, r0.w
					add o1.w, -r0.w, l(1.000000)
					mad r0.xyz, v1.xyzx, -r1.xxxx, r0.xyzx
					mul r1.xyz, -r0.yyyy, cb0[1].xyzx
					mad r0.xyw, cb0[0].xyxz, -r0.xxxx, r1.xyxz
					mad o1.xyz, cb0[2].xyzx, -r0.zzzz, r0.xywx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					// TEXCOORD                 1      w        1     NONE   float      w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texturecube (float,float,float,float) t0
					dcl_resource_texturecube (float,float,float,float) t1
					dcl_input_ps linear v1.xyz
					dcl_input_ps linear v1.w
					dcl_output o0.xyzw
					dcl_temps 3
					sample r0.xyzw, v1.xyzx, t1.xyzw, s0
					add r0.w, r0.w, l(-1.000000)
					mad r0.w, cb1[3].w, r0.w, l(1.000000)
					log r0.w, r0.w
					mul r0.w, r0.w, cb1[3].y
					exp r0.w, r0.w
					mul r0.w, r0.w, cb1[3].x
					mul r0.xyz, r0.xyzx, r0.wwww
					mad r1.xyz, r0.xyzx, cb0[3].yyyy, cb0[3].zzzz
					mul r0.xyz, r0.xyzx, cb0[3].xxxx
					sample r2.xyzw, v1.xyzx, t0.xyzw, s1
					mul r2.xyz, r2.xyzx, cb0[2].xyzx
					mul r1.xyz, r1.xyzx, r2.xyzx
					mad o0.xyz, r0.xyzx, v1.wwww, r1.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					// TEXCOORD                 1      w        1     NONE   float      w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texturecube (float,float,float,float) t0
					dcl_resource_texturecube (float,float,float,float) t1
					dcl_input_ps linear v1.xyz
					dcl_input_ps linear v1.w
					dcl_output o0.xyzw
					dcl_temps 3
					sample r0.xyzw, v1.xyzx, t1.xyzw, s0
					add r0.w, r0.w, l(-1.000000)
					mad r0.w, cb1[3].w, r0.w, l(1.000000)
					log r0.w, r0.w
					mul r0.w, r0.w, cb1[3].y
					exp r0.w, r0.w
					mul r0.w, r0.w, cb1[3].x
					mul r0.xyz, r0.xyzx, r0.wwww
					mad r1.xyz, r0.xyzx, cb0[3].yyyy, cb0[3].zzzz
					mul r0.xyz, r0.xyzx, cb0[3].xxxx
					sample r2.xyzw, v1.xyzx, t0.xyzw, s1
					mul r2.xyz, r2.xyzx, cb0[2].xyzx
					mul r1.xyz, r1.xyzx, r2.xyzx
					mad o0.xyz, r0.xyzx, v1.wwww, r1.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		UsePass "VertexLit/SHADOWCASTER"
	}
}