Shader "Lexicon/Shake" {
	Properties {
		_Intensity ("Intensity", Range(0, 50)) = 0
		_Speed ("Speed", Range(0, 50)) = 1
		_ColorTintR (" Red Tint", Range(0, 1)) = 0
		_ColorTintB (" Blue Tint", Range(0, 1)) = 0
		_ColorTintG (" Green Tint", Range(0, 1)) = 0
		[Toggle(_Dark)] _Dark ("Bright/Dark", Float) = 0
	}
	SubShader {
		Tags { "QUEUE" = "Overlay" "RenderType" = "Overlay" }
		GrabPass {
			"_GrabTexture"
		}
		Pass {
			Tags { "QUEUE" = "Overlay" "RenderType" = "Overlay" }
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 221
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o2.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					mul r0.xyzw, r1.yyyy, cb2[18].xyzw
					mad r0.xyzw, cb2[17].xyzw, r1.xxxx, r0.xyzw
					mad r0.xyzw, cb2[19].xyzw, r1.zzzz, r0.xyzw
					mad r0.xyzw, cb2[20].xyzw, r1.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					mul r2.xyz, r0.xywx, l(0.500000, 0.500000, 0.500000, 0.000000)
					mul r2.w, r2.y, cb0[5].x
					add r0.xy, r2.zzzz, r2.xwxx
					mov o1.xyzw, r0.xyzw
					mov o3.xyw, r0.xyxw
					mul r0.x, r1.y, cb2[10].z
					mad r0.x, cb2[9].z, r1.x, r0.x
					mad r0.x, cb2[11].z, r1.z, r0.x
					mad r0.x, cb2[12].z, r1.w, r0.x
					mov o3.z, -r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[68], dynamicIndexed
					dcl_constantbuffer CB3[1], immediateIndexed
					dcl_input v0.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyzw
					dcl_temps 4
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o2.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					ishl r0.x, cb3[0].x, l(2)
					mul r2.xyzw, r1.yyyy, cb2[r0.x + 25].xyzw
					mad r2.xyzw, cb2[r0.x + 24].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 26].xyzw, r1.zzzz, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 27].xyzw, r1.wwww, r2.xyzw
					mov o0.xyzw, r2.xyzw
					mul r3.xyz, r2.xywx, l(0.500000, 0.500000, 0.500000, 0.000000)
					mul r3.w, r3.y, cb0[4].x
					add r0.yz, r3.zzzz, r3.xxwx
					mov r0.w, cb3[0].x
					mul r3.xy, r2.wwww, cb2[r0.w + 66].zwzz
					mad r2.xy, r0.yzyy, cb2[r0.w + 66].xyxx, r3.xyxx
					mov o1.xyzw, r2.xyzw
					mov o3.xyw, r2.xyxw
					mul r0.y, r1.y, cb2[r0.x + 9].z
					mad r0.y, cb2[r0.x + 8].z, r1.x, r0.y
					mad r0.y, cb2[r0.x + 10].z, r1.z, r0.y
					mad r0.x, cb2[r0.x + 11].z, r1.w, r0.y
					mov o3.z, -r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_Dark" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o2.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					mul r0.xyzw, r1.yyyy, cb2[18].xyzw
					mad r0.xyzw, cb2[17].xyzw, r1.xxxx, r0.xyzw
					mad r0.xyzw, cb2[19].xyzw, r1.zzzz, r0.xyzw
					mad r0.xyzw, cb2[20].xyzw, r1.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					mul r2.xyz, r0.xywx, l(0.500000, 0.500000, 0.500000, 0.000000)
					mul r2.w, r2.y, cb0[5].x
					add r0.xy, r2.zzzz, r2.xwxx
					mov o1.xyzw, r0.xyzw
					mov o3.xyw, r0.xyxw
					mul r0.x, r1.y, cb2[10].z
					mad r0.x, cb2[9].z, r1.x, r0.x
					mad r0.x, cb2[11].z, r1.z, r0.x
					mad r0.x, cb2[12].z, r1.w, r0.x
					mov o3.z, -r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_SINGLE_PASS_STEREO" "_Dark" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[68], dynamicIndexed
					dcl_constantbuffer CB3[1], immediateIndexed
					dcl_input v0.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyzw
					dcl_temps 4
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o2.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					ishl r0.x, cb3[0].x, l(2)
					mul r2.xyzw, r1.yyyy, cb2[r0.x + 25].xyzw
					mad r2.xyzw, cb2[r0.x + 24].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 26].xyzw, r1.zzzz, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 27].xyzw, r1.wwww, r2.xyzw
					mov o0.xyzw, r2.xyzw
					mul r3.xyz, r2.xywx, l(0.500000, 0.500000, 0.500000, 0.000000)
					mul r3.w, r3.y, cb0[4].x
					add r0.yz, r3.zzzz, r3.xxwx
					mov r0.w, cb3[0].x
					mul r3.xy, r2.wwww, cb2[r0.w + 66].zwzz
					mad r2.xy, r0.yzyy, cb2[r0.w + 66].xyxx, r3.xyxx
					mov o1.xyzw, r2.xyzw
					mov o3.xyw, r2.xyxw
					mul r0.y, r1.y, cb2[r0.x + 9].z
					mad r0.y, cb2[r0.x + 8].z, r1.x, r0.y
					mad r0.y, cb2[r0.x + 10].z, r1.z, r0.y
					mad r0.x, cb2[r0.x + 11].z, r1.w, r0.y
					mov o3.z, -r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        2     NONE   float       
					// TEXCOORD                 2   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_output o0.xyzw
					dcl_temps 1
					mad r0.x, cb1[0].y, cb0[2].y, v1.z
					mul r0.x, r0.x, cb0[2].x
					sincos r0.x, null, r0.x
					mad r0.xy, r0.xxxx, l(0.100000, 0.100000, 0.000000, 0.000000), v1.xyxx
					div r0.xy, r0.xyxx, v1.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					add o0.y, r0.y, cb0[3].x
					add o0.xz, r0.xxzx, cb0[2].zzwz
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        2     NONE   float       
					// TEXCOORD                 2   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_output o0.xyzw
					dcl_temps 1
					mad r0.x, cb1[0].y, cb0[2].y, v1.z
					mul r0.x, r0.x, cb0[2].x
					sincos r0.x, null, r0.x
					mad r0.xy, r0.xxxx, l(0.100000, 0.100000, 0.000000, 0.000000), v1.xyxx
					div r0.xy, r0.xyxx, v1.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					add o0.y, r0.y, cb0[3].x
					add o0.xz, r0.xxzx, cb0[2].zzwz
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_Dark" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        2     NONE   float       
					// TEXCOORD                 2   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_output o0.xyzw
					dcl_temps 1
					mad r0.x, cb1[0].y, cb0[2].y, v1.z
					mul r0.x, r0.x, cb0[2].x
					sincos r0.x, null, r0.x
					mad r0.xy, r0.xxxx, l(0.100000, 0.100000, 0.000000, 0.000000), v1.xyxx
					div r0.xy, r0.xyxx, v1.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mul o0.y, r0.y, cb0[3].x
					mul o0.xz, r0.xxzx, cb0[2].zzwz
					mov o0.w, r0.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_SINGLE_PASS_STEREO" "_Dark" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        2     NONE   float       
					// TEXCOORD                 2   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_output o0.xyzw
					dcl_temps 1
					mad r0.x, cb1[0].y, cb0[2].y, v1.z
					mul r0.x, r0.x, cb0[2].x
					sincos r0.x, null, r0.x
					mad r0.xy, r0.xxxx, l(0.100000, 0.100000, 0.000000, 0.000000), v1.xyxx
					div r0.xy, r0.xyxx, v1.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mul o0.y, r0.y, cb0[3].x
					mul o0.xz, r0.xxzx, cb0[2].zzwz
					mov o0.w, r0.w
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	Fallback "Diffuse"
}