Shader "MAG/Blackhole" {
	Properties {
		_DistortionStrength ("Distortion Strength", Range(0, 10)) = 3.020896
		_HoleSize ("Hole Size", Range(0, 1)) = 0.7030833
		_HoleEdgeSmoothness ("Hole Edge Smoothness", Range(0.001, 0.05)) = 0.007289694
	}
	SubShader {
		Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
		GrabPass {
		}
		Pass {
			Name "FORWARD"
			Tags { "IGNOREPROJECTOR" = "true" "LIGHTMODE" = "FORWARDBASE" "QUEUE" = "Transparent" "RenderType" = "Transparent" "SHADOWSUPPORT" = "true" }
			ZWrite Off
			GpuProgramID 27221
			Program "vp" {
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyz
					dcl_output o3.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					mul r0.xyzw, r1.yyyy, cb2[18].xyzw
					mad r0.xyzw, cb2[17].xyzw, r1.xxxx, r0.xyzw
					mad r0.xyzw, cb2[19].xyzw, r1.zzzz, r0.xyzw
					mad r0.xyzw, cb2[20].xyzw, r1.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					dp3 r2.x, v1.xyzx, cb1[4].xyzx
					dp3 r2.y, v1.xyzx, cb1[5].xyzx
					dp3 r2.z, v1.xyzx, cb1[6].xyzx
					dp3 r0.z, r2.xyzx, r2.xyzx
					rsq r0.z, r0.z
					mul o2.xyz, r0.zzzz, r2.xyzx
					mul r0.z, r1.y, cb2[10].z
					mad r0.z, cb2[9].z, r1.x, r0.z
					mad r0.z, cb2[11].z, r1.z, r0.z
					mad r0.z, cb2[12].z, r1.w, r0.z
					mov o3.z, -r0.z
					mul r0.y, r0.y, cb0[5].x
					mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o3.w, r0.w
					add o3.xy, r1.zzzz, r1.xwxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[68], dynamicIndexed
					dcl_constantbuffer CB3[1], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyz
					dcl_output o3.xyzw
					dcl_temps 4
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					ishl r0.x, cb3[0].x, l(2)
					mul r2.xyzw, r1.yyyy, cb2[r0.x + 25].xyzw
					mad r2.xyzw, cb2[r0.x + 24].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 26].xyzw, r1.zzzz, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 27].xyzw, r1.wwww, r2.xyzw
					mov o0.xyzw, r2.xyzw
					dp3 r3.x, v1.xyzx, cb1[4].xyzx
					dp3 r3.y, v1.xyzx, cb1[5].xyzx
					dp3 r3.z, v1.xyzx, cb1[6].xyzx
					dp3 r0.y, r3.xyzx, r3.xyzx
					rsq r0.y, r0.y
					mul o2.xyz, r0.yyyy, r3.xyzx
					mul r0.y, r1.y, cb2[r0.x + 9].z
					mad r0.y, cb2[r0.x + 8].z, r1.x, r0.y
					mad r0.y, cb2[r0.x + 10].z, r1.z, r0.y
					mad r0.x, cb2[r0.x + 11].z, r1.w, r0.y
					mov o3.z, -r0.x
					mul r0.x, r2.y, cb0[4].x
					mul r0.w, r0.x, l(0.500000)
					mul r0.xz, r2.xxwx, l(0.500000, 0.000000, 0.500000, 0.000000)
					add r0.xy, r0.zzzz, r0.xwxx
					mov r0.z, cb3[0].x
					mul r1.xy, r2.wwww, cb2[r0.z + 66].zwzz
					mad o3.xy, r0.xyxx, cb2[r0.z + 66].xyxx, r1.xyxx
					mov o3.w, r2.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "LIGHTPROBE_SH" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyz
					dcl_output o3.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					mul r0.xyzw, r1.yyyy, cb2[18].xyzw
					mad r0.xyzw, cb2[17].xyzw, r1.xxxx, r0.xyzw
					mad r0.xyzw, cb2[19].xyzw, r1.zzzz, r0.xyzw
					mad r0.xyzw, cb2[20].xyzw, r1.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					dp3 r2.x, v1.xyzx, cb1[4].xyzx
					dp3 r2.y, v1.xyzx, cb1[5].xyzx
					dp3 r2.z, v1.xyzx, cb1[6].xyzx
					dp3 r0.z, r2.xyzx, r2.xyzx
					rsq r0.z, r0.z
					mul o2.xyz, r0.zzzz, r2.xyzx
					mul r0.z, r1.y, cb2[10].z
					mad r0.z, cb2[9].z, r1.x, r0.z
					mad r0.z, cb2[11].z, r1.z, r0.z
					mad r0.z, cb2[12].z, r1.w, r0.z
					mov o3.z, -r0.z
					mul r0.y, r0.y, cb0[5].x
					mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o3.w, r0.w
					add o3.xy, r1.zzzz, r1.xwxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "LIGHTPROBE_SH" "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[68], dynamicIndexed
					dcl_constantbuffer CB3[1], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyz
					dcl_output o3.xyzw
					dcl_temps 4
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					ishl r0.x, cb3[0].x, l(2)
					mul r2.xyzw, r1.yyyy, cb2[r0.x + 25].xyzw
					mad r2.xyzw, cb2[r0.x + 24].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 26].xyzw, r1.zzzz, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 27].xyzw, r1.wwww, r2.xyzw
					mov o0.xyzw, r2.xyzw
					dp3 r3.x, v1.xyzx, cb1[4].xyzx
					dp3 r3.y, v1.xyzx, cb1[5].xyzx
					dp3 r3.z, v1.xyzx, cb1[6].xyzx
					dp3 r0.y, r3.xyzx, r3.xyzx
					rsq r0.y, r0.y
					mul o2.xyz, r0.yyyy, r3.xyzx
					mul r0.y, r1.y, cb2[r0.x + 9].z
					mad r0.y, cb2[r0.x + 8].z, r1.x, r0.y
					mad r0.y, cb2[r0.x + 10].z, r1.z, r0.y
					mad r0.x, cb2[r0.x + 11].z, r1.w, r0.y
					mov o3.z, -r0.x
					mul r0.x, r2.y, cb0[4].x
					mul r0.w, r0.x, l(0.500000)
					mul r0.xz, r2.xxwx, l(0.500000, 0.000000, 0.500000, 0.000000)
					add r0.xy, r0.zzzz, r0.xwxx
					mov r0.z, cb3[0].x
					mul r1.xy, r2.wwww, cb2[r0.z + 66].zwzz
					mad o3.xy, r0.xyxx, cb2[r0.z + 66].xyxx, r1.xyxx
					mov o3.w, r2.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyz
					dcl_output o3.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					mul r0.xyzw, r1.yyyy, cb2[18].xyzw
					mad r0.xyzw, cb2[17].xyzw, r1.xxxx, r0.xyzw
					mad r0.xyzw, cb2[19].xyzw, r1.zzzz, r0.xyzw
					mad r0.xyzw, cb2[20].xyzw, r1.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					dp3 r2.x, v1.xyzx, cb1[4].xyzx
					dp3 r2.y, v1.xyzx, cb1[5].xyzx
					dp3 r2.z, v1.xyzx, cb1[6].xyzx
					dp3 r0.z, r2.xyzx, r2.xyzx
					rsq r0.z, r0.z
					mul o2.xyz, r0.zzzz, r2.xyzx
					mul r0.z, r1.y, cb2[10].z
					mad r0.z, cb2[9].z, r1.x, r0.z
					mad r0.z, cb2[11].z, r1.z, r0.z
					mad r0.z, cb2[12].z, r1.w, r0.z
					mov o3.z, -r0.z
					mul r0.y, r0.y, cb0[5].x
					mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o3.w, r0.w
					add o3.xy, r1.zzzz, r1.xwxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[68], dynamicIndexed
					dcl_constantbuffer CB3[1], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyz
					dcl_output o3.xyzw
					dcl_temps 4
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					ishl r0.x, cb3[0].x, l(2)
					mul r2.xyzw, r1.yyyy, cb2[r0.x + 25].xyzw
					mad r2.xyzw, cb2[r0.x + 24].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 26].xyzw, r1.zzzz, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 27].xyzw, r1.wwww, r2.xyzw
					mov o0.xyzw, r2.xyzw
					dp3 r3.x, v1.xyzx, cb1[4].xyzx
					dp3 r3.y, v1.xyzx, cb1[5].xyzx
					dp3 r3.z, v1.xyzx, cb1[6].xyzx
					dp3 r0.y, r3.xyzx, r3.xyzx
					rsq r0.y, r0.y
					mul o2.xyz, r0.yyyy, r3.xyzx
					mul r0.y, r1.y, cb2[r0.x + 9].z
					mad r0.y, cb2[r0.x + 8].z, r1.x, r0.y
					mad r0.y, cb2[r0.x + 10].z, r1.z, r0.y
					mad r0.x, cb2[r0.x + 11].z, r1.w, r0.y
					mov o3.z, -r0.x
					mul r0.x, r2.y, cb0[4].x
					mul r0.w, r0.x, l(0.500000)
					mul r0.xz, r2.xxwx, l(0.500000, 0.000000, 0.500000, 0.000000)
					add r0.xy, r0.zzzz, r0.xwxx
					mov r0.z, cb3[0].x
					mul r1.xy, r2.wwww, cb2[r0.z + 66].zwzz
					mad o3.xy, r0.xyxx, cb2[r0.z + 66].xyxx, r1.xyxx
					mov o3.w, r2.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "LIGHTPROBE_SH" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyz
					dcl_output o3.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					mul r0.xyzw, r1.yyyy, cb2[18].xyzw
					mad r0.xyzw, cb2[17].xyzw, r1.xxxx, r0.xyzw
					mad r0.xyzw, cb2[19].xyzw, r1.zzzz, r0.xyzw
					mad r0.xyzw, cb2[20].xyzw, r1.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					dp3 r2.x, v1.xyzx, cb1[4].xyzx
					dp3 r2.y, v1.xyzx, cb1[5].xyzx
					dp3 r2.z, v1.xyzx, cb1[6].xyzx
					dp3 r0.z, r2.xyzx, r2.xyzx
					rsq r0.z, r0.z
					mul o2.xyz, r0.zzzz, r2.xyzx
					mul r0.z, r1.y, cb2[10].z
					mad r0.z, cb2[9].z, r1.x, r0.z
					mad r0.z, cb2[11].z, r1.z, r0.z
					mad r0.z, cb2[12].z, r1.w, r0.z
					mov o3.z, -r0.z
					mul r0.y, r0.y, cb0[5].x
					mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o3.w, r0.w
					add o3.xy, r1.zzzz, r1.xwxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "LIGHTPROBE_SH" "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[68], dynamicIndexed
					dcl_constantbuffer CB3[1], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyz
					dcl_output o3.xyzw
					dcl_temps 4
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					ishl r0.x, cb3[0].x, l(2)
					mul r2.xyzw, r1.yyyy, cb2[r0.x + 25].xyzw
					mad r2.xyzw, cb2[r0.x + 24].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 26].xyzw, r1.zzzz, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 27].xyzw, r1.wwww, r2.xyzw
					mov o0.xyzw, r2.xyzw
					dp3 r3.x, v1.xyzx, cb1[4].xyzx
					dp3 r3.y, v1.xyzx, cb1[5].xyzx
					dp3 r3.z, v1.xyzx, cb1[6].xyzx
					dp3 r0.y, r3.xyzx, r3.xyzx
					rsq r0.y, r0.y
					mul o2.xyz, r0.yyyy, r3.xyzx
					mul r0.y, r1.y, cb2[r0.x + 9].z
					mad r0.y, cb2[r0.x + 8].z, r1.x, r0.y
					mad r0.y, cb2[r0.x + 10].z, r1.z, r0.y
					mad r0.x, cb2[r0.x + 11].z, r1.w, r0.y
					mov o3.z, -r0.x
					mul r0.x, r2.y, cb0[4].x
					mul r0.w, r0.x, l(0.500000)
					mul r0.xz, r2.xxwx, l(0.500000, 0.000000, 0.500000, 0.000000)
					add r0.xy, r0.zzzz, r0.xwxx
					mov r0.z, cb3[0].x
					mul r1.xy, r2.wwww, cb2[r0.z + 66].zwzz
					mad o3.xy, r0.xyxx, cb2[r0.z + 66].xyxx, r1.xyxx
					mov o3.w, r2.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "VERTEXLIGHT_ON" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyz
					dcl_output o3.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					mul r0.xyzw, r1.yyyy, cb2[18].xyzw
					mad r0.xyzw, cb2[17].xyzw, r1.xxxx, r0.xyzw
					mad r0.xyzw, cb2[19].xyzw, r1.zzzz, r0.xyzw
					mad r0.xyzw, cb2[20].xyzw, r1.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					dp3 r2.x, v1.xyzx, cb1[4].xyzx
					dp3 r2.y, v1.xyzx, cb1[5].xyzx
					dp3 r2.z, v1.xyzx, cb1[6].xyzx
					dp3 r0.z, r2.xyzx, r2.xyzx
					rsq r0.z, r0.z
					mul o2.xyz, r0.zzzz, r2.xyzx
					mul r0.z, r1.y, cb2[10].z
					mad r0.z, cb2[9].z, r1.x, r0.z
					mad r0.z, cb2[11].z, r1.z, r0.z
					mad r0.z, cb2[12].z, r1.w, r0.z
					mov o3.z, -r0.z
					mul r0.y, r0.y, cb0[5].x
					mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o3.w, r0.w
					add o3.xy, r1.zzzz, r1.xwxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "VERTEXLIGHT_ON" "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[68], dynamicIndexed
					dcl_constantbuffer CB3[1], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyz
					dcl_output o3.xyzw
					dcl_temps 4
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					ishl r0.x, cb3[0].x, l(2)
					mul r2.xyzw, r1.yyyy, cb2[r0.x + 25].xyzw
					mad r2.xyzw, cb2[r0.x + 24].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 26].xyzw, r1.zzzz, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 27].xyzw, r1.wwww, r2.xyzw
					mov o0.xyzw, r2.xyzw
					dp3 r3.x, v1.xyzx, cb1[4].xyzx
					dp3 r3.y, v1.xyzx, cb1[5].xyzx
					dp3 r3.z, v1.xyzx, cb1[6].xyzx
					dp3 r0.y, r3.xyzx, r3.xyzx
					rsq r0.y, r0.y
					mul o2.xyz, r0.yyyy, r3.xyzx
					mul r0.y, r1.y, cb2[r0.x + 9].z
					mad r0.y, cb2[r0.x + 8].z, r1.x, r0.y
					mad r0.y, cb2[r0.x + 10].z, r1.z, r0.y
					mad r0.x, cb2[r0.x + 11].z, r1.w, r0.y
					mov o3.z, -r0.x
					mul r0.x, r2.y, cb0[4].x
					mul r0.w, r0.x, l(0.500000)
					mul r0.xz, r2.xxwx, l(0.500000, 0.000000, 0.500000, 0.000000)
					add r0.xy, r0.zzzz, r0.xwxx
					mov r0.z, cb3[0].x
					mul r1.xy, r2.wwww, cb2[r0.z + 66].zwzz
					mad o3.xy, r0.xyxx, cb2[r0.z + 66].xyxx, r1.xyxx
					mov o3.w, r2.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "LIGHTPROBE_SH" "VERTEXLIGHT_ON" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyz
					dcl_output o3.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					mul r0.xyzw, r1.yyyy, cb2[18].xyzw
					mad r0.xyzw, cb2[17].xyzw, r1.xxxx, r0.xyzw
					mad r0.xyzw, cb2[19].xyzw, r1.zzzz, r0.xyzw
					mad r0.xyzw, cb2[20].xyzw, r1.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					dp3 r2.x, v1.xyzx, cb1[4].xyzx
					dp3 r2.y, v1.xyzx, cb1[5].xyzx
					dp3 r2.z, v1.xyzx, cb1[6].xyzx
					dp3 r0.z, r2.xyzx, r2.xyzx
					rsq r0.z, r0.z
					mul o2.xyz, r0.zzzz, r2.xyzx
					mul r0.z, r1.y, cb2[10].z
					mad r0.z, cb2[9].z, r1.x, r0.z
					mad r0.z, cb2[11].z, r1.z, r0.z
					mad r0.z, cb2[12].z, r1.w, r0.z
					mov o3.z, -r0.z
					mul r0.y, r0.y, cb0[5].x
					mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o3.w, r0.w
					add o3.xy, r1.zzzz, r1.xwxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "LIGHTPROBE_SH" "VERTEXLIGHT_ON" "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[68], dynamicIndexed
					dcl_constantbuffer CB3[1], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyz
					dcl_output o3.xyzw
					dcl_temps 4
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					ishl r0.x, cb3[0].x, l(2)
					mul r2.xyzw, r1.yyyy, cb2[r0.x + 25].xyzw
					mad r2.xyzw, cb2[r0.x + 24].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 26].xyzw, r1.zzzz, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 27].xyzw, r1.wwww, r2.xyzw
					mov o0.xyzw, r2.xyzw
					dp3 r3.x, v1.xyzx, cb1[4].xyzx
					dp3 r3.y, v1.xyzx, cb1[5].xyzx
					dp3 r3.z, v1.xyzx, cb1[6].xyzx
					dp3 r0.y, r3.xyzx, r3.xyzx
					rsq r0.y, r0.y
					mul o2.xyz, r0.yyyy, r3.xyzx
					mul r0.y, r1.y, cb2[r0.x + 9].z
					mad r0.y, cb2[r0.x + 8].z, r1.x, r0.y
					mad r0.y, cb2[r0.x + 10].z, r1.z, r0.y
					mad r0.x, cb2[r0.x + 11].z, r1.w, r0.y
					mov o3.z, -r0.x
					mul r0.x, r2.y, cb0[4].x
					mul r0.w, r0.x, l(0.500000)
					mul r0.xz, r2.xxwx, l(0.500000, 0.000000, 0.500000, 0.000000)
					add r0.xy, r0.zzzz, r0.xwxx
					mov r0.z, cb3[0].x
					mul r1.xy, r2.wwww, cb2[r0.z + 66].zwzz
					mad o3.xy, r0.xyxx, cb2[r0.z + 66].xyxx, r1.xyxx
					mov o3.w, r2.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "VERTEXLIGHT_ON" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyz
					dcl_output o3.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					mul r0.xyzw, r1.yyyy, cb2[18].xyzw
					mad r0.xyzw, cb2[17].xyzw, r1.xxxx, r0.xyzw
					mad r0.xyzw, cb2[19].xyzw, r1.zzzz, r0.xyzw
					mad r0.xyzw, cb2[20].xyzw, r1.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					dp3 r2.x, v1.xyzx, cb1[4].xyzx
					dp3 r2.y, v1.xyzx, cb1[5].xyzx
					dp3 r2.z, v1.xyzx, cb1[6].xyzx
					dp3 r0.z, r2.xyzx, r2.xyzx
					rsq r0.z, r0.z
					mul o2.xyz, r0.zzzz, r2.xyzx
					mul r0.z, r1.y, cb2[10].z
					mad r0.z, cb2[9].z, r1.x, r0.z
					mad r0.z, cb2[11].z, r1.z, r0.z
					mad r0.z, cb2[12].z, r1.w, r0.z
					mov o3.z, -r0.z
					mul r0.y, r0.y, cb0[5].x
					mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o3.w, r0.w
					add o3.xy, r1.zzzz, r1.xwxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "VERTEXLIGHT_ON" "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[68], dynamicIndexed
					dcl_constantbuffer CB3[1], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyz
					dcl_output o3.xyzw
					dcl_temps 4
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					ishl r0.x, cb3[0].x, l(2)
					mul r2.xyzw, r1.yyyy, cb2[r0.x + 25].xyzw
					mad r2.xyzw, cb2[r0.x + 24].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 26].xyzw, r1.zzzz, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 27].xyzw, r1.wwww, r2.xyzw
					mov o0.xyzw, r2.xyzw
					dp3 r3.x, v1.xyzx, cb1[4].xyzx
					dp3 r3.y, v1.xyzx, cb1[5].xyzx
					dp3 r3.z, v1.xyzx, cb1[6].xyzx
					dp3 r0.y, r3.xyzx, r3.xyzx
					rsq r0.y, r0.y
					mul o2.xyz, r0.yyyy, r3.xyzx
					mul r0.y, r1.y, cb2[r0.x + 9].z
					mad r0.y, cb2[r0.x + 8].z, r1.x, r0.y
					mad r0.y, cb2[r0.x + 10].z, r1.z, r0.y
					mad r0.x, cb2[r0.x + 11].z, r1.w, r0.y
					mov o3.z, -r0.x
					mul r0.x, r2.y, cb0[4].x
					mul r0.w, r0.x, l(0.500000)
					mul r0.xz, r2.xxwx, l(0.500000, 0.000000, 0.500000, 0.000000)
					add r0.xy, r0.zzzz, r0.xwxx
					mov r0.z, cb3[0].x
					mul r1.xy, r2.wwww, cb2[r0.z + 66].zwzz
					mad o3.xy, r0.xyxx, cb2[r0.z + 66].xyxx, r1.xyxx
					mov o3.w, r2.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "LIGHTPROBE_SH" "VERTEXLIGHT_ON" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyz
					dcl_output o3.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					mul r0.xyzw, r1.yyyy, cb2[18].xyzw
					mad r0.xyzw, cb2[17].xyzw, r1.xxxx, r0.xyzw
					mad r0.xyzw, cb2[19].xyzw, r1.zzzz, r0.xyzw
					mad r0.xyzw, cb2[20].xyzw, r1.wwww, r0.xyzw
					mov o0.xyzw, r0.xyzw
					dp3 r2.x, v1.xyzx, cb1[4].xyzx
					dp3 r2.y, v1.xyzx, cb1[5].xyzx
					dp3 r2.z, v1.xyzx, cb1[6].xyzx
					dp3 r0.z, r2.xyzx, r2.xyzx
					rsq r0.z, r0.z
					mul o2.xyz, r0.zzzz, r2.xyzx
					mul r0.z, r1.y, cb2[10].z
					mad r0.z, cb2[9].z, r1.x, r0.z
					mad r0.z, cb2[11].z, r1.z, r0.z
					mad r0.z, cb2[12].z, r1.w, r0.z
					mov o3.z, -r0.z
					mul r0.y, r0.y, cb0[5].x
					mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o3.w, r0.w
					add o3.xy, r1.zzzz, r1.xwxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "LIGHTPROBE_SH" "VERTEXLIGHT_ON" "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[68], dynamicIndexed
					dcl_constantbuffer CB3[1], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyz
					dcl_output o3.xyzw
					dcl_temps 4
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					ishl r0.x, cb3[0].x, l(2)
					mul r2.xyzw, r1.yyyy, cb2[r0.x + 25].xyzw
					mad r2.xyzw, cb2[r0.x + 24].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 26].xyzw, r1.zzzz, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 27].xyzw, r1.wwww, r2.xyzw
					mov o0.xyzw, r2.xyzw
					dp3 r3.x, v1.xyzx, cb1[4].xyzx
					dp3 r3.y, v1.xyzx, cb1[5].xyzx
					dp3 r3.z, v1.xyzx, cb1[6].xyzx
					dp3 r0.y, r3.xyzx, r3.xyzx
					rsq r0.y, r0.y
					mul o2.xyz, r0.yyyy, r3.xyzx
					mul r0.y, r1.y, cb2[r0.x + 9].z
					mad r0.y, cb2[r0.x + 8].z, r1.x, r0.y
					mad r0.y, cb2[r0.x + 10].z, r1.z, r0.y
					mad r0.x, cb2[r0.x + 11].z, r1.w, r0.y
					mov o3.z, -r0.x
					mul r0.x, r2.y, cb0[4].x
					mul r0.w, r0.x, l(0.500000)
					mul r0.xz, r2.xxwx, l(0.500000, 0.000000, 0.500000, 0.000000)
					add r0.xy, r0.zzzz, r0.xwxx
					mov r0.z, cb3[0].x
					mul r1.xy, r2.wwww, cb2[r0.z + 66].zwzz
					mad o3.xy, r0.xyxx, cb2[r0.z + 66].xyxx, r1.xyxx
					mov o3.w, r2.w
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyz 
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyz
					dcl_input_ps linear v2.xyz
					dcl_input_ps linear v3.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					add r0.xyz, -v1.xyzx, cb1[4].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.w, v2.xyzx, v2.xyzx
					rsq r0.w, r0.w
					mul r1.xyz, r0.wwww, v2.xyzx
					dp3 r0.x, r1.xyzx, r0.xyzx
					max r0.x, r0.x, l(0.000000)
					add r0.x, -r0.x, l(1.000000)
					log r0.x, r0.x
					mul r0.y, r0.x, l(0.150000)
					mul r0.x, r0.x, cb0[2].x
					exp r0.x, r0.x
					add r0.x, -r0.x, l(1.000000)
					exp r0.y, r0.y
					add r0.y, -r0.y, l(1.000000)
					add r0.z, -cb0[2].y, l(1.000000)
					add r0.w, r0.z, cb0[2].z
					add r0.z, r0.z, -cb0[2].z
					add r0.yz, -r0.wwww, r0.yyzy
					div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
					mul_sat r0.y, r0.z, r0.y
					mad r0.z, r0.y, l(-2.000000), l(3.000000)
					mul r0.y, r0.y, r0.y
					mul r0.xy, r0.xyxx, r0.xzxx
					mul r0.z, r0.x, r0.x
					mul r0.x, r0.z, r0.x
					div r0.zw, v3.xxxy, v3.wwww
					mad r1.xy, r0.zwzz, l(-2.000000, -2.000000, 0.000000, 0.000000), l(1.000000, 1.000000, 0.000000, 0.000000)
					mad r0.xz, r0.xxxx, r1.xxyx, r0.zzwz
					sample r1.xyzw, r0.xzxx, t0.xyzw, s0
					mul o0.xyz, r0.yyyy, r1.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyz 
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[66], dynamicIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyz
					dcl_input_ps linear v2.xyz
					dcl_input_ps linear v3.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					mov r0.x, cb2[0].x
					add r0.xyz, -v1.xyzx, cb1[r0.x + 64].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.w, v2.xyzx, v2.xyzx
					rsq r0.w, r0.w
					mul r1.xyz, r0.wwww, v2.xyzx
					dp3 r0.x, r1.xyzx, r0.xyzx
					max r0.x, r0.x, l(0.000000)
					add r0.x, -r0.x, l(1.000000)
					log r0.x, r0.x
					mul r0.y, r0.x, l(0.150000)
					mul r0.x, r0.x, cb0[2].x
					exp r0.x, r0.x
					add r0.x, -r0.x, l(1.000000)
					exp r0.y, r0.y
					add r0.y, -r0.y, l(1.000000)
					add r0.z, -cb0[2].y, l(1.000000)
					add r0.w, r0.z, cb0[2].z
					add r0.z, r0.z, -cb0[2].z
					add r0.yz, -r0.wwww, r0.yyzy
					div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
					mul_sat r0.y, r0.z, r0.y
					mad r0.z, r0.y, l(-2.000000), l(3.000000)
					mul r0.y, r0.y, r0.y
					mul r0.xy, r0.xyxx, r0.xzxx
					mul r0.z, r0.x, r0.x
					mul r0.x, r0.z, r0.x
					div r0.zw, v3.xxxy, v3.wwww
					mad r1.xy, r0.zwzz, l(-2.000000, -2.000000, 0.000000, 0.000000), l(1.000000, 1.000000, 0.000000, 0.000000)
					mad r0.xz, r0.xxxx, r1.xxyx, r0.zzwz
					sample r1.xyzw, r0.xzxx, t0.xyzw, s0
					mul o0.xyz, r0.yyyy, r1.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "LIGHTPROBE_SH" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyz 
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyz
					dcl_input_ps linear v2.xyz
					dcl_input_ps linear v3.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					add r0.xyz, -v1.xyzx, cb1[4].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.w, v2.xyzx, v2.xyzx
					rsq r0.w, r0.w
					mul r1.xyz, r0.wwww, v2.xyzx
					dp3 r0.x, r1.xyzx, r0.xyzx
					max r0.x, r0.x, l(0.000000)
					add r0.x, -r0.x, l(1.000000)
					log r0.x, r0.x
					mul r0.y, r0.x, l(0.150000)
					mul r0.x, r0.x, cb0[2].x
					exp r0.x, r0.x
					add r0.x, -r0.x, l(1.000000)
					exp r0.y, r0.y
					add r0.y, -r0.y, l(1.000000)
					add r0.z, -cb0[2].y, l(1.000000)
					add r0.w, r0.z, cb0[2].z
					add r0.z, r0.z, -cb0[2].z
					add r0.yz, -r0.wwww, r0.yyzy
					div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
					mul_sat r0.y, r0.z, r0.y
					mad r0.z, r0.y, l(-2.000000), l(3.000000)
					mul r0.y, r0.y, r0.y
					mul r0.xy, r0.xyxx, r0.xzxx
					mul r0.z, r0.x, r0.x
					mul r0.x, r0.z, r0.x
					div r0.zw, v3.xxxy, v3.wwww
					mad r1.xy, r0.zwzz, l(-2.000000, -2.000000, 0.000000, 0.000000), l(1.000000, 1.000000, 0.000000, 0.000000)
					mad r0.xz, r0.xxxx, r1.xxyx, r0.zzwz
					sample r1.xyzw, r0.xzxx, t0.xyzw, s0
					mul o0.xyz, r0.yyyy, r1.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "LIGHTPROBE_SH" "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyz 
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[66], dynamicIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyz
					dcl_input_ps linear v2.xyz
					dcl_input_ps linear v3.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					mov r0.x, cb2[0].x
					add r0.xyz, -v1.xyzx, cb1[r0.x + 64].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.w, v2.xyzx, v2.xyzx
					rsq r0.w, r0.w
					mul r1.xyz, r0.wwww, v2.xyzx
					dp3 r0.x, r1.xyzx, r0.xyzx
					max r0.x, r0.x, l(0.000000)
					add r0.x, -r0.x, l(1.000000)
					log r0.x, r0.x
					mul r0.y, r0.x, l(0.150000)
					mul r0.x, r0.x, cb0[2].x
					exp r0.x, r0.x
					add r0.x, -r0.x, l(1.000000)
					exp r0.y, r0.y
					add r0.y, -r0.y, l(1.000000)
					add r0.z, -cb0[2].y, l(1.000000)
					add r0.w, r0.z, cb0[2].z
					add r0.z, r0.z, -cb0[2].z
					add r0.yz, -r0.wwww, r0.yyzy
					div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
					mul_sat r0.y, r0.z, r0.y
					mad r0.z, r0.y, l(-2.000000), l(3.000000)
					mul r0.y, r0.y, r0.y
					mul r0.xy, r0.xyxx, r0.xzxx
					mul r0.z, r0.x, r0.x
					mul r0.x, r0.z, r0.x
					div r0.zw, v3.xxxy, v3.wwww
					mad r1.xy, r0.zwzz, l(-2.000000, -2.000000, 0.000000, 0.000000), l(1.000000, 1.000000, 0.000000, 0.000000)
					mad r0.xz, r0.xxxx, r1.xxyx, r0.zzwz
					sample r1.xyzw, r0.xzxx, t0.xyzw, s0
					mul o0.xyz, r0.yyyy, r1.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyz 
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyz
					dcl_input_ps linear v2.xyz
					dcl_input_ps linear v3.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					add r0.xyz, -v1.xyzx, cb1[4].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.w, v2.xyzx, v2.xyzx
					rsq r0.w, r0.w
					mul r1.xyz, r0.wwww, v2.xyzx
					dp3 r0.x, r1.xyzx, r0.xyzx
					max r0.x, r0.x, l(0.000000)
					add r0.x, -r0.x, l(1.000000)
					log r0.x, r0.x
					mul r0.y, r0.x, l(0.150000)
					mul r0.x, r0.x, cb0[2].x
					exp r0.x, r0.x
					add r0.x, -r0.x, l(1.000000)
					exp r0.y, r0.y
					add r0.y, -r0.y, l(1.000000)
					add r0.z, -cb0[2].y, l(1.000000)
					add r0.w, r0.z, cb0[2].z
					add r0.z, r0.z, -cb0[2].z
					add r0.yz, -r0.wwww, r0.yyzy
					div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
					mul_sat r0.y, r0.z, r0.y
					mad r0.z, r0.y, l(-2.000000), l(3.000000)
					mul r0.y, r0.y, r0.y
					mul r0.xy, r0.xyxx, r0.xzxx
					mul r0.z, r0.x, r0.x
					mul r0.x, r0.z, r0.x
					div r0.zw, v3.xxxy, v3.wwww
					mad r1.xy, r0.zwzz, l(-2.000000, -2.000000, 0.000000, 0.000000), l(1.000000, 1.000000, 0.000000, 0.000000)
					mad r0.xz, r0.xxxx, r1.xxyx, r0.zzwz
					sample r1.xyzw, r0.xzxx, t0.xyzw, s0
					mul o0.xyz, r0.yyyy, r1.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyz 
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[66], dynamicIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyz
					dcl_input_ps linear v2.xyz
					dcl_input_ps linear v3.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					mov r0.x, cb2[0].x
					add r0.xyz, -v1.xyzx, cb1[r0.x + 64].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.w, v2.xyzx, v2.xyzx
					rsq r0.w, r0.w
					mul r1.xyz, r0.wwww, v2.xyzx
					dp3 r0.x, r1.xyzx, r0.xyzx
					max r0.x, r0.x, l(0.000000)
					add r0.x, -r0.x, l(1.000000)
					log r0.x, r0.x
					mul r0.y, r0.x, l(0.150000)
					mul r0.x, r0.x, cb0[2].x
					exp r0.x, r0.x
					add r0.x, -r0.x, l(1.000000)
					exp r0.y, r0.y
					add r0.y, -r0.y, l(1.000000)
					add r0.z, -cb0[2].y, l(1.000000)
					add r0.w, r0.z, cb0[2].z
					add r0.z, r0.z, -cb0[2].z
					add r0.yz, -r0.wwww, r0.yyzy
					div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
					mul_sat r0.y, r0.z, r0.y
					mad r0.z, r0.y, l(-2.000000), l(3.000000)
					mul r0.y, r0.y, r0.y
					mul r0.xy, r0.xyxx, r0.xzxx
					mul r0.z, r0.x, r0.x
					mul r0.x, r0.z, r0.x
					div r0.zw, v3.xxxy, v3.wwww
					mad r1.xy, r0.zwzz, l(-2.000000, -2.000000, 0.000000, 0.000000), l(1.000000, 1.000000, 0.000000, 0.000000)
					mad r0.xz, r0.xxxx, r1.xxyx, r0.zzwz
					sample r1.xyzw, r0.xzxx, t0.xyzw, s0
					mul o0.xyz, r0.yyyy, r1.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "LIGHTPROBE_SH" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyz 
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyz
					dcl_input_ps linear v2.xyz
					dcl_input_ps linear v3.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					add r0.xyz, -v1.xyzx, cb1[4].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.w, v2.xyzx, v2.xyzx
					rsq r0.w, r0.w
					mul r1.xyz, r0.wwww, v2.xyzx
					dp3 r0.x, r1.xyzx, r0.xyzx
					max r0.x, r0.x, l(0.000000)
					add r0.x, -r0.x, l(1.000000)
					log r0.x, r0.x
					mul r0.y, r0.x, l(0.150000)
					mul r0.x, r0.x, cb0[2].x
					exp r0.x, r0.x
					add r0.x, -r0.x, l(1.000000)
					exp r0.y, r0.y
					add r0.y, -r0.y, l(1.000000)
					add r0.z, -cb0[2].y, l(1.000000)
					add r0.w, r0.z, cb0[2].z
					add r0.z, r0.z, -cb0[2].z
					add r0.yz, -r0.wwww, r0.yyzy
					div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
					mul_sat r0.y, r0.z, r0.y
					mad r0.z, r0.y, l(-2.000000), l(3.000000)
					mul r0.y, r0.y, r0.y
					mul r0.xy, r0.xyxx, r0.xzxx
					mul r0.z, r0.x, r0.x
					mul r0.x, r0.z, r0.x
					div r0.zw, v3.xxxy, v3.wwww
					mad r1.xy, r0.zwzz, l(-2.000000, -2.000000, 0.000000, 0.000000), l(1.000000, 1.000000, 0.000000, 0.000000)
					mad r0.xz, r0.xxxx, r1.xxyx, r0.zzwz
					sample r1.xyzw, r0.xzxx, t0.xyzw, s0
					mul o0.xyz, r0.yyyy, r1.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "SHADOWS_SCREEN" "LIGHTPROBE_SH" "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyz 
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        3     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[66], dynamicIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyz
					dcl_input_ps linear v2.xyz
					dcl_input_ps linear v3.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					mov r0.x, cb2[0].x
					add r0.xyz, -v1.xyzx, cb1[r0.x + 64].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.w, v2.xyzx, v2.xyzx
					rsq r0.w, r0.w
					mul r1.xyz, r0.wwww, v2.xyzx
					dp3 r0.x, r1.xyzx, r0.xyzx
					max r0.x, r0.x, l(0.000000)
					add r0.x, -r0.x, l(1.000000)
					log r0.x, r0.x
					mul r0.y, r0.x, l(0.150000)
					mul r0.x, r0.x, cb0[2].x
					exp r0.x, r0.x
					add r0.x, -r0.x, l(1.000000)
					exp r0.y, r0.y
					add r0.y, -r0.y, l(1.000000)
					add r0.z, -cb0[2].y, l(1.000000)
					add r0.w, r0.z, cb0[2].z
					add r0.z, r0.z, -cb0[2].z
					add r0.yz, -r0.wwww, r0.yyzy
					div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
					mul_sat r0.y, r0.z, r0.y
					mad r0.z, r0.y, l(-2.000000), l(3.000000)
					mul r0.y, r0.y, r0.y
					mul r0.xy, r0.xyxx, r0.xzxx
					mul r0.z, r0.x, r0.x
					mul r0.x, r0.z, r0.x
					div r0.zw, v3.xxxy, v3.wwww
					mad r1.xy, r0.zwzz, l(-2.000000, -2.000000, 0.000000, 0.000000), l(1.000000, 1.000000, 0.000000, 0.000000)
					mad r0.xz, r0.xxxx, r1.xxyx, r0.zzwz
					sample r1.xyzw, r0.xzxx, t0.xyzw, s0
					mul o0.xyz, r0.yyyy, r1.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	Fallback "Diffuse"
	CustomEditor "ShaderForgeMaterialInspector"
}