Shader "Mochie/MSFX Zoom" {
	Properties {
		[HideInInspector] _BlendMode ("__mode", Float) = 0
		[HideInInspector] _SrcBlend ("__src", Float) = 1
		[HideInInspector] _DstBlend ("__dst", Float) = 0
		[Toggle(PULZ)] _PulseToggle ("UV Pulse", Float) = 0
		_PulseSpeed ("Speed", Range(0.5, 8)) = 1
		[Enum(NONE,0, SINZ,1, SAWZ,2, REVSAWZ,3, SQUAREZ,4, TRIANGLEZ,5)] _Waveform ("Waveform", Float) = 0
		_Opacity ("Opacity", Range(0, 1)) = 1
		_Magnification ("Magnification", Range(1, 3)) = 1
		_MaxRange ("Max Range", Range(0.1, 50)) = 8
	}
	SubShader {
		Tags { "FORCENOSHADOWCASTING" = "true" "IGNOREPROJECTOR" = "true" "LIGHTMODE" = "ALWAYS" "QUEUE" = "Overlay+2" }
		GrabPass {
			"_gpMSFXZoom"
		}
		Pass {
			Tags { "FORCENOSHADOWCASTING" = "true" "IGNOREPROJECTOR" = "true" "LIGHTMODE" = "ALWAYS" "QUEUE" = "Overlay+2" }
			Blend Zero Zero, Zero Zero
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 29578
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_constantbuffer CB2[22], immediateIndexed
					dcl_constantbuffer CB3[8], immediateIndexed
					dcl_constantbuffer CB4[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb2[19].xyzw
					mad r0.xyzw, cb2[18].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb2[20].xyzw, v0.zzzz, r0.xyzw
					mad r0.xyzw, cb2[21].xyzw, v0.wwww, r0.xyzw
					mul r1.xyz, r0.yyyy, cb3[5].xyzx
					mad r1.xyz, cb3[4].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb3[6].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb3[7].xyzx, r0.wwww, r0.xyzx
					mul r1.xyzw, r0.yyyy, cb3[1].xyzw
					mad r1.xyzw, cb3[0].xyzw, r0.xxxx, r1.xyzw
					mad r0.xyzw, cb3[2].xyzw, r0.zzzz, r1.xyzw
					add r0.xyzw, r0.xyzw, cb3[3].xyzw
					mul r1.xyzw, r0.yyyy, cb4[18].xyzw
					mad r1.xyzw, cb4[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb4[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb4[20].xyzw, r0.wwww, r1.xyzw
					add r1.xyz, cb1[4].xyzx, -cb3[3].xyzx
					dp3 r1.x, r1.xyzx, r1.xyzx
					sqrt r1.xyzw, r1.xxxx
					ge r2.x, r1.w, cb0[0].y
					mov o2.xyzw, r1.xyzw
					and r1.x, r2.x, l(0x3f800000)
					mad r0.xyzw, -r0.xyzw, r1.xxxx, r0.xyzw
					mov o0.xyzw, r0.xyzw
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					add r0.xy, r1.yyyy, r1.xzxx
					mul r1.xyzw, v0.yyyy, cb3[1].xyzw
					mad r1.xyzw, cb3[0].xyzw, v0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[2].xyzw, v0.zzzz, r1.xyzw
					add r1.xyzw, r1.xyzw, cb3[3].xyzw
					mul r2.xyzw, r1.yyyy, cb4[18].xyzw
					mad r2.xyzw, cb4[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb4[19].xyzw, r1.zzzz, r2.xyzw
					mad r1.xyzw, cb4[20].xyzw, r1.wwww, r2.xyzw
					mul r2.xyz, r1.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					add r1.xy, r2.yyyy, r2.xzxx
					add r0.xyzw, r0.xyzw, -r1.xyzw
					div r0.xyzw, r0.xyzw, cb0[0].xxxx
					add o1.xyzw, r0.xyzw, r1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_constantbuffer CB1[8], immediateIndexed
					dcl_constantbuffer CB2[68], dynamicIndexed
					dcl_constantbuffer CB3[1], immediateIndexed
					dcl_input v0.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 4
					ishl r0.x, cb3[0].x, l(2)
					mul r1.xyzw, v0.yyyy, cb2[r0.x + 57].xyzw
					mad r1.xyzw, cb2[r0.x + 56].xyzw, v0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[r0.x + 58].xyzw, v0.zzzz, r1.xyzw
					mad r1.xyzw, cb2[r0.x + 59].xyzw, v0.wwww, r1.xyzw
					mul r0.yzw, r1.yyyy, cb1[5].xxyz
					mad r0.yzw, cb1[4].xxyz, r1.xxxx, r0.yyzw
					mad r0.yzw, cb1[6].xxyz, r1.zzzz, r0.yyzw
					mad r0.yzw, cb1[7].xxyz, r1.wwww, r0.yyzw
					mul r1.xyzw, r0.zzzz, cb1[1].xyzw
					mad r1.xyzw, cb1[0].xyzw, r0.yyyy, r1.xyzw
					mad r1.xyzw, cb1[2].xyzw, r0.wwww, r1.xyzw
					add r1.xyzw, r1.xyzw, cb1[3].xyzw
					mul r2.xyzw, r1.yyyy, cb2[r0.x + 25].xyzw
					mad r2.xyzw, cb2[r0.x + 24].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[r0.x + 26].xyzw, r1.zzzz, r2.xyzw
					mad r1.xyzw, cb2[r0.x + 27].xyzw, r1.wwww, r2.xyzw
					mov r0.y, cb3[0].x
					add r2.xyz, -cb1[3].xyzx, cb2[r0.y + 64].xyzx
					dp3 r0.z, r2.xyzx, r2.xyzx
					sqrt r2.xyzw, r0.zzzz
					ge r0.z, r2.w, cb0[0].y
					mov o2.xyzw, r2.xyzw
					and r0.z, r0.z, l(0x3f800000)
					mad r1.xyzw, -r1.xyzw, r0.zzzz, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mul r2.xyzw, v0.yyyy, cb1[1].xyzw
					mad r2.xyzw, cb1[0].xyzw, v0.xxxx, r2.xyzw
					mad r2.xyzw, cb1[2].xyzw, v0.zzzz, r2.xyzw
					add r2.xyzw, r2.xyzw, cb1[3].xyzw
					mul r3.xyzw, r2.yyyy, cb2[r0.x + 25].xyzw
					mad r3.xyzw, cb2[r0.x + 24].xyzw, r2.xxxx, r3.xyzw
					mad r3.xyzw, cb2[r0.x + 26].xyzw, r2.zzzz, r3.xyzw
					mad r2.xyzw, cb2[r0.x + 27].xyzw, r2.wwww, r3.xyzw
					mul r0.xzw, r2.xxwy, l(0.500000, 0.000000, 0.500000, -0.500000)
					add r0.xz, r0.zzzz, r0.xxwx
					mul r3.xy, r2.wwww, cb2[r0.y + 66].zwzz
					mad r2.xy, r0.xzxx, cb2[r0.y + 66].xyxx, r3.xyxx
					mul r0.xz, r1.wwww, cb2[r0.y + 66].zzwz
					mul r3.xyz, r1.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					add r3.xy, r3.yyyy, r3.xzxx
					mad r1.xy, r3.xyxx, cb2[r0.y + 66].xyxx, r0.xzxx
					add r0.xyzw, -r2.xyzw, r1.xyzw
					div r0.xyzw, r0.xyzw, cb0[0].xxxx
					add o1.xyzw, r0.xyzw, r2.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xy w
					// TEXCOORD                 1   xyzw        2     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyw
					dcl_output o0.xyzw
					dcl_temps 1
					div r0.xy, v1.xyxx, v1.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mov o0.xyz, r0.xyzx
					mov o0.w, cb0[0].z
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_SINGLE_PASS_STEREO" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xy w
					// TEXCOORD                 1   xyzw        2     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyw
					dcl_output o0.xyzw
					dcl_temps 1
					div r0.xy, v1.xyxx, v1.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mov o0.xyz, r0.xyzx
					mov o0.w, cb0[0].z
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	Fallback "Diffuse"
	CustomEditor "MZEditor"
}